{{- if and .Values.enabled (or .Values.job.enabled .Values.cronJob.enabled) .Values.jobTemplate.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "job.serviceAccountName" . }}
  labels:
    {{- include "job.labels" . | nindent 4 }}
  {{- with .Values.jobTemplate.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.jobTemplate.serviceAccount.automount }}
{{- end }}
