{{- if and .Values.enabled .Values.image.fluxImageAutoUpdate.enabled }}
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  imageRepositoryRef:
    name: {{ include "microservice.fullname" . }}
  filterTags:
    {{- if .Values.image.fluxImageAutoUpdate.pattern }}
    pattern: {{ .Values.image.fluxImageAutoUpdate.pattern | quote }}
    {{- end }}
  policy:
    semver:
      range: {{ .Values.image.fluxImageAutoUpdate.semver | quote }}
{{- end }}
