{{- if and .Values.enabled .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (include "microservice.fullname" .) .Values.pvc.name }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    {{- toYaml .Values.pvc.resources | nindent 4 }}
{{- end }}
